version: '3.9'

services:
  api01: &api
    # image: nicolasmmb/a-go-rinha:latest
    build: .
    depends_on:
      database: 
          condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.175'
          memory: '32MB'
    environment:
      SERVER_PORT: 9999
      SERVER_ADDR: 0.0.0.0
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: rinha
      DB_PASS: rinha
      DB_NAME: rinha

  api02:
    <<: *api


  database:
    image: postgres
    hostname: database
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    volumes:
      - ./config/init.v2.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '450MB'
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha

  nginx: 
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
      - database
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '16MB'
    ports:
      - "9999:9999"
    # network_mode: "host"
    # extra_hosts:
    #   - "api01:0.0.0.0"
    #   - "api02:0.0.0.0"
    

  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    hostname: pgbouncer
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '16MB'
    ports:
      - "6432:6432" 
    environment:
      - POSTGRESQL_HOST=database
      - POSTGRESQL_PASSWORD=rinha
      - POSTGRESQL_USERNAME=rinha
      - PGBOUNCER_DATABASE=*
      - PGBOUNCER_TRANSACTION_POOL_SIZE=300
      - PGBOUNCER_MAX_CLIENT_CONN=300
      - PGBOUNCER_DEFAULT_POOL_SIZE=200
      - PGBOUNCER_MIN_POOL_SIZE=150
      # - PGBOUNCER_RESERVE_POOL_SIZE=5
      # - PGBOUNCER_RESERVE_POOL_TIMEOUT=5
      # - PGBOUNCER_SERVER_IDLE_TIMEOUT=240
      # - PGBOUNCER_SERVER_RESET_QUERY=DISCARD ALL
      # # transaction type: session, statement, transaction
      - PGBOUNCER_POOL_MODE=transaction
      